/*
   FINAL PROJECT
   We are using 2 .cpp files
   1) The assembler. We read instructions from a file that we have designed.
   We determine what the instructions look like. The assembler will create another file
   that stores the binary.
   2) Use a simulator to read the binary generated by the assembler. We will have
   functions that take care of reading the parts of the binary and break it up.
 
*/

#include <registermap>
#include <iostream>
#include <fstream>
#include <cstdlib>
using namespace std;

string reg_to_bin(string reg);

int main()
{
    
    // making a map
    map<string, int> reg_map;   // this is how we initialize a map
    reg_map["000"] = 0;         // to initialize the values in a map; can add more as needed
    ifstream fin("sum.carlos");
    if(fin.fail())
    {
            cout << "File open failed\n";
            exit(0);
    }
    
    stirng opcode;
    
    fin >> opcode;

    if(opcode == "PUT")
    {
        out << "0011";
        fin >> num;
        out << dec_to_binary(num);

    }


}

string reg_to_bin(string reg)
{
    if(reg == "R1")
        return "000";
    else if(reg == "R2")
        return "001";
    else if(reg == "R3")
        return "010";
    else if(reg == "R4")
        return "011";
    else if(reg == "R5")
        return "100";
    else if(reg == "R6")
        return "101";
    else if(reg == "R7")
        return "110";
    else if(reg == "R8")
        return "111";
    else
        return "Invalid register\n";

}
